## Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
# Creating list of 5 integers
numbers = [10, 20, 30, 40, 50]
print(numbers)

[10, 20, 30, 40, 50]

In [3]:
numbers.append(60) #append means add to item to end of the list
print("append:", numbers)

append: [10, 20, 30, 40, 50, 60]

In [4]:
numbers.extend([70, 80]) #add multiple items to end of the list
print("extend:", numbers)

extend: [10, 20, 30, 40, 50, 60, 70, 80]

In [5]:
numbers.insert(2, 25) # inserts element at a specific position
print("insert:", numbers)

insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]

In [6]:
numbers.remove(40) #removes the item at value based.
print("remove:", numbers)

remove: [10, 20, 25, 30, 50, 60, 70, 80]

In [7]:
numbers.pop(3) #remove the item using index based
print("pop:", numbers)

pop: [10, 20, 25, 50, 60, 70, 80]

In [15]:
numbers.clear() #clears all items in the list
print("clear:", numbers)

clear: []

In [9]:
print("Index of 20:", numbers.index(20)) #returns index value

Index of 20: 1

In [10]:
print("Count of 20:", numbers.count(20)) #it counts the number of occurances

Count of 20: 1

In [12]:
 numbers.sort() #sort the llist in asscending order
print("sort:", numbers)

sort: [10, 20, 25, 50, 60, 70, 80]

In [13]:
numbers.reverse() #reverse the list
print("reverse:", numbers)

reverse: [80, 70, 60, 50, 25, 20, 10]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [16]:
# Creating tuple with 3 student names
students = ("Rahul", "Anita", "Ravi")

print("tuple:", students)

students[1] = "Priya"

print(students)

tuple: ('Rahul', 'Anita', 'Ravi')

TypeError: 'tuple' object does not support item assignment

Explanation:

A tuple in Python is immutable.

Immutable means its values cannot be changed after creation.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [17]:
# Creating set with duplicate values
numbers = {10, 20, 30, 20, 40, 10, 50}

print("Set values:", numbers)

Set values: {50, 20, 40, 10, 30}

Explanation:

A set in Python does not allow duplicate values.

When the set is created, Python automatically removes duplicate elements.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [18]:
# Creating  dictionary
person = {
    "name": "Rahul",
    "age": 22,
    "city": "Bangalore"
}

print("dictionary:", person)

# Update age
person["age"] = 23

# Add new key 'email'
person["email"] = "uday@example.com"

# Print final dictionary
print("Final dictionary:", person)

dictionary: {'name': 'Rahul', 'age': 22, 'city': 'Bangalore'}
Final dictionary: {'name': 'Rahul', 'age': 23, 'city': 'Bangalore', 'email': 'uday@example.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [19]:
# Age variable
age = 20

# Check voting eligibility
if age >= 18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")

The person is eligible to vote.

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [20]:
# Marks variable
marks = 82

# Check grade
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [21]:
# Given number
num = 8

# Check conditions
if num > 0:
    print("The number is positive.")
    
    if num % 2 == 0:
        print("The number is also even.")
    else:
        print("The number is odd.")

elif num == 0:
    print("The number is zero.")

else:
    print("The number is negative.")

The number is positive.
The number is also even.

## Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [27]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D Array:\n", array_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [26]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, (4, 4))

print("4x4 Random Array:\n", random_array)

4x4 Random Array:
 [[ 4 97 34  4]
 [62 61 55  8]
 [64 84 72 27]
 [52 37 18 57]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [28]:
import numpy as np
import pandas as pd

# Create a 2D numpy array (3x3)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Convert numpy array to pandas DataFrame with column names
df = pd.DataFrame(array, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [67]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# Creating DataFrame with 10 rows
data = {
    "Name": ["uday", "Anita", "Ravi", "Priya", "Kiran", "Sneha", "Arjun", "Meena", "Ravi", "Priya"],
    "Age": [22, 23, 21, 24, 22, 23, 25, 21, 21, 24],
    "City": ["Delhi", "Mumbai", "Chennai", "Bangalore", "Hyderabad", "Pune", "Delhi", "Mumbai", "Chennai", "Bangalore"],
    "Salary": [50000, 60000, np.nan, 55000, 52000, np.nan, 65000, 48000, 50000, 55000]
       }

df = pd.DataFrame(data)

print("DataFrame:\n", df)

DataFrame:
     Name  Age       City   Salary
0   uday   22      Delhi  50000.0
1  Anita   23     Mumbai  60000.0
2   Ravi   21    Chennai      NaN
3  Priya   24  Bangalore  55000.0
4  Kiran   22  Hyderabad  52000.0
5  Sneha   23       Pune      NaN
6  Arjun   25      Delhi  65000.0
7  Meena   21     Mumbai  48000.0
8   Ravi   21    Chennai  50000.0
9  Priya   24  Bangalore  55000.0

use info

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      object
 1   Age     9 non-null      int64
 2   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 288.0+ bytes

use describe

In [69]:
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   22.600000  54375.000000
std     1.429841   5730.557191
min    21.000000  48000.000000
25%    21.250000  50000.000000
50%    22.500000  53500.000000
75%    23.750000  56250.000000
max    25.000000  65000.000000

Select 'Name' and 'City' columns

In [70]:
df[['Name', 'City']]

    Name       City
0   uday      Delhi
1  Anita     Mumbai
2   Ravi    Chennai
3  Priya  Bangalore
4  Kiran  Hyderabad
5  Sneha       Pune
6  Arjun      Delhi
7  Meena     Mumbai
8   Ravi    Chennai
9  Priya  Bangalore

Drop 'City' column

In [71]:
df = df.drop('City', axis=1)
print(df)

    Name  Age   Salary
0   uday   22  50000.0
1  Anita   23  60000.0
2   Ravi   21      NaN
3  Priya   24  55000.0
4  Kiran   22  52000.0
5  Sneha   23      NaN
6  Arjun   25  65000.0
7  Meena   21  48000.0
8   Ravi   21  50000.0
9  Priya   24  55000.0

Fill any missing values in 'Salary' column with the mean

In [72]:
df['Salary']=df['Salary'].fillna(value=df['Salary'].mean())
print(df)

    Name  Age   Salary
0   uday   22  50000.0
1  Anita   23  60000.0
2   Ravi   21  54375.0
3  Priya   24  55000.0
4  Kiran   22  52000.0
5  Sneha   23  54375.0
6  Arjun   25  65000.0
7  Meena   21  48000.0
8   Ravi   21  50000.0
9  Priya   24  55000.0

Remove the duplicate rows

In [73]:
df = df.drop_duplicates()
print(df)

    Name  Age   Salary
0   uday   22  50000.0
1  Anita   23  60000.0
2   Ravi   21  54375.0
3  Priya   24  55000.0
4  Kiran   22  52000.0
5  Sneha   23  54375.0
6  Arjun   25  65000.0
7  Meena   21  48000.0
8   Ravi   21  50000.0